Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.define "worker1"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "private_network", type: "dhcp"
#config.vm.network :private_network, ip: '192.168.69.170'
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = 2048
     vb.cpus = 2
     vb.name = "kubernetes-worker1"
  end
end
