IMAGE_NAME = "bento/ubuntu-20.04"
K8S_NAME = "dw-k8s-01"
MASTERS_NUM = 1
MASTERS_CPU = 2 
MASTERS_MEM = 2048

NODES_NUM = 3
NODES_CPU = 2
NODES_MEM = 1024

IP_BASE = "192.168.50."

VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  (1..NODES_NUM).each do |j|
    config.vm.define "k8-node-#{j}" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.network "private_network", ip: "#{IP_BASE}#{j + 10 + MASTERS_NUM}"
      node.vm.hostname = "k8s-node-#{j}"
      
    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = NODES_MEM
      v.cpus = NODES_CPU
      end
      node.vm.provision :shell, path: "bootstrap.sh"          
    end
  end
end
