Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.define "worker4"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = 2048
     vb.cpus = 2
     vb.name = "kubernetes-worker4"
  end
end
